import {
    Box,
    Text
} from '@chakra-ui/react'

import PageContainer from '../components/PageContainer/PageContainer'
import Sidebar from '../components/Sidebar/Sidebar'
import Footer from '../components/Footer/Footer'
import { API_CATEGORIES_URL } from '../utils/urls'
import SectionHeader from '../components/SectionHeader/SectionHeader'
import SectionSubHeader from '../components/SectionSubHeader/SectionSubHeader'
import ParagraphSection from '../components/ParagraphSection/ParagraphSection'

export default function privacy({ categories }) {

    return (
        <Box minH='100vh'>
            <Sidebar categories={categories} />
            <PageContainer>
                <SectionHeader>
                    Privacy Policy
                </SectionHeader>
                <SectionSubHeader>
                    Last Updated: 19/10/21
                </SectionSubHeader>
                <ParagraphSection
                    text='This Privacy Policy describes our policies and procedures on how we collect, use and disclose the information provided when you use our site.

                        MyPets uses your personal data to provide and improve our service & platform. By using our platform, you agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the [Privacy Policy Generator](https://www.freeprivacypolicy.com/free-privacy-policy-generator/).
                        
                        The term MyPets/MyPets Singapore refers to the same entity.'
                />
                <ParagraphSection
                    heading='Definitions'
                />
                <ParagraphSection
                    heading='For the purposes of this Privacy Policy:'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Account means a unique account created in order to use our site.'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Company (referred to as either the Company, We, Us or Our in this Agreement) refers to MyPets Singapore.'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Cookies are small files that are placed on your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Device means any device that can access our platform such as a computer, a cell phone or a digital tablet.'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Personal Data is any information provided by you upon signing up with MyPets.'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Service/Platform refers to our website'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Service Provider means any natural or legal person who processes the data on behalf of MyPets. It refers to third-party companies or individuals employed by MyPets to facilitate the service, to provide the service on behalf of MyPets, to perform services related to the service or to assist the MyPets in analysing how the service is used.'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Third-party Social Media Service refers to any social network website through which a User can log in or create an account to use our Service.'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Usage Data refers to data collected automatically, either generated by the use of the service or from the Service infrastructure itself (for example, the duration of a page visit).'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Website refers to MyPets Singapore, accessible from [www.mypets.sg](https://cdpn.io/cp/internal/boomboom/mypets.sg)'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- You refer to the account owner or representatives on behalf of the account owner that is accessing our service'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Website refers to MyPets Singapore, accessible from [www.mypets.sg](https://cdpn.io/cp/internal/boomboom/mypets.sg)'
                />
                <ParagraphSection
                    heading='Data Collection & Usage'
                />
                <ParagraphSection
                    heading='Types Of Data Collected'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    heading='Personal Data'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='When using our service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. (Personal Data) may include, but is not limited to:'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Email address'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- First name and last name'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Phone number'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Address, State, Province, ZIP/Postal code, City'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Cookies & Usage Data'
                />
                <ParagraphSection
                    heading='Usage Data'
                    text='Usage Data is collected automatically when you use our service. We may take information regarding your devices Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                    Likewise, when accessing our service through a mobile device, we may also collect information regarding, the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, it&#39;s mobile operating system, the type of mobile Internet browser that you use, unique device identifiers and other diagnostic data.'
                />
                <ParagraphSection
                    heading='Information From Third-Party Social Media Services'
                    text='MyPets allows you to create an account and log in to use our service through the following third-party social media services:'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Google'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Facebook'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='If you decide to register through a third-party social media service, we may collect personal data that is already associated with them. 
                    By signing up with either of the above third-party social media service providers, you are aware & have granted us the permission to use, share, and store it in a manner consistent with this Privacy Policy.'
                />
                <ParagraphSection
                    heading='Collection of data (Cookies)'
                    text='We use Cookies to track the activity on our service and store certain information.
                    Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='We use cookies for our service for the following purposes:'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Enabling certain features and functions on our websites, e.g. remembering your details, browsing and other services preferences'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Building up a profile of how you and other users use the website'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Improving the efficiency of our website'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Establishing usage statistics'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Administering services to you and to advertisers'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='You can choose to opt out all cookies or indicate when a cookie is being sent. However, there might be a case where you may not be able to use some portions of our service.'
                />
                <ParagraphSection
                    heading='Personal Data Use'
                    text='We may use your Personal Data for the following purposes:'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Provide and maintain our service.'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Provide access to current functions & inform you about new functions that can benefit you as a registered user.'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Carry out orders efficiently & improve your shopping experience'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Inform you about necessary promotions, products & newly onboard merchants'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Inform you about special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased, unless you have opted not to receive such information.'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Provide customer care & support for you'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Address & fix technical issue'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Notify you about changes to our service and regular maintenance'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Improve our business operations by with the help of data analytics'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='We may share your personal information:'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- With business partners to offer you certain products, services or promotions.'
                />
                <ParagraphSection
                    heading='Retention Of Your Personal Data'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='The Company will retain your personal data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your personal data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                    We will also retain usage data for internal analysis purposes. Usage data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our service, or we are legally obligated to retain this data for longer time periods.'
                />
                <ParagraphSection
                    heading='Data Transfer'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='Your information, including Personal Data, may be transferred to — and maintained on — computers located outside Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.

                    Your consent to this Privacy policy followed by submission of your personal information represents Your agreement to that transfer.
                    
                    We will take all steps necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.'
                    // mb={{ base: 3 }}
                />
                <ParagraphSection
                    heading='Disclosure Of Data'
                />
                <ParagraphSection
                    heading='Regulations'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='MyPets may disclose your Personal Data in the good faith belief that such action is necessary to:'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Comply with a legal obligation'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Protect and defend the rights or property of the Company'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Prevent or investigate possible wrongdoing in connection with the Service'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Protect the personal safety of Users of the Service or the public'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- Protect against legal liability'
                />
                <ParagraphSection
                    heading='Security of your personal data'
                    text='The security of your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.'
                />
                <ParagraphSection
                    heading='Childrens Privacy'
                    text='Our service does not address anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. If You are a parent or guardian, and you are aware that your child has provided us with personal data, please inform us. If We become aware that we have collected personal data from anyone under the age of 18 without verification of parental consent, We will take the necessary steps to remove that information from our servers.'
                />
                <ParagraphSection
                    heading='Links To Other Websites'
                    text='Our Service may contain links to other websites that are not operated by us. If you click on a third party link, You will be directed to that third partys site. We strongly advise you to review the Privacy Policy of every site you visit.
                    We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.'
                />
                <ParagraphSection
                    heading='Changes To This Privacy Policy'
                    text='We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
                    We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective, and update the "Last updated" date at the top of this Privacy Policy.
                    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.'
                />
                <ParagraphSection
                    heading="Contact Us"
                    text='If you have any questions about this Privacy Policy, you can contact us:'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- By email: contactmypetssg@gmail.com'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- By visiting this page on our website: [www.mypets.sg](https://cdpn.io/cp/internal/boomboom/www.mypets.sg)'
                />
                <ParagraphSection
                    heading="Delivery"
                    text='If you have any questions about this Privacy Policy, you can contact us:'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- By email: contactmypetssg@gmail.com'
                    mb={{ base: 3 }}
                />
                <ParagraphSection
                    text='- By visiting this page on our website: [www.mypets.sg](https://cdpn.io/cp/internal/boomboom/www.mypets.sg)'
                />
            </PageContainer>
        </Box>
    )
}

export async function getStaticProps() {
    // Fetch categories
    const categories_res = await fetch(`${API_CATEGORIES_URL}`)
    const categories = await categories_res.json()

    // Return as props
    return {
        props: {
            categories,
        }
    }
}