import React from "react";

const Sitemap = () => { };

export const getServerSideProps = ({ res }) => {
    const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
    <urlset
        xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"
    >
        <url>
            <loc>https://www.mypets.sg/</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>1.00</priority>
            </url>
        <url>
            <loc>https://www.mypets.sg/merchants/Taste-Of-The-Wild</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/merchants/aatas-cat</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
            <url>
            <loc>https://www.mypets.sg/merchants/absorb-plus</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
            <url>
            <loc>https://www.mypets.sg/merchants/Bronco</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
            <url>
            <loc>https://www.mypets.sg/merchants/kit-cat</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/merchants/project-luni</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/kit-cat-gourmet-boneless-chicken-shreds-and-shrimp</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/kit-cat-deboned-tuna-and-salmon-toppers</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/kit-cat-atlantic-tuna-with-whole-anchovy</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/kit-cat-deboned-tuna-and-chicken-toppers</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/kit-cat-deboned-tuna-and-whitebait-toppers</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/kit-cat-deboned-chicken-classic-toppers</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/kit-cat-deboned-chicken-and-beef-toppers</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/kit-cat-gourmet-boneless-chicken-shreds-and-crab-meat</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/cod-pate-adult</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/kit-cat-gourmet-boneless-chicken-shreds-and-salmon</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/kit-cat-gourmet-white-meat-tuna-flakes-and-salmon</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/kit-cat-atlantic-tuna-with-wild-salmon</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/salmon-pate-dogs</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/kit-cat-atlantic-tuna-with-tender-chicken</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/kit-cat-deboned-chicken-and-salmon-toppers</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/turkey-pate-adult</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/aatas-cat-kuick-klump-bentonite-cat-litter-lemongrass</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/aatas-cat-kuick-klump-bentonite-cat-litter-ocean-breeze</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/aatas-cat-kuick-klump-bentonite-cat-litter-peppermint</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/absorb-plus-charcoal-pet-sheets-pee-pad</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/taste-of-the-wild-rocky-mountain-roasted-venison-and-smoked-salmon</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/taste-of-the-wild-pacific-stream-with-smoked-salmon</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/products/luni-2022-calendar</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/about</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/contact</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/faq</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/terms-conditions</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://www.mypets.sg/privacy-policy</loc>
            <lastmod>2022-01-10T23:25:04+00:00</lastmod>
            <priority>0.80</priority>
        </url>
    </urlset>`;

    res.setHeader("Content-Type", "text/xml");
    res.write(sitemap);
    res.end();

    return {
        props: {},
    };
};

export default Sitemap;